[package]
name = "obs-preview"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
env_logger = { workspace = true }
libobs-wrapper = { workspace = true }
libobs-simple = { workspace = true }
winit = { workspace = true }
