[package]
name = "download-at-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
env_logger = "0.11.8"
indicatif = "0.18.3"
libobs-bootstrapper = { workspace = true }
libobs-wrapper = { workspace = true }
tokio = { version = "1.44.1", features = ["full"] }
